apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploytest
  namespace: test
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: multi
    spec:
      containers:
        - name: multi-pipline
          image: nginx
          ports:
            - containerPort: 8090
  strategy:
    type: RollingUpdate
