apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  namespace: test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: container-test
        image: nginx
        resources:                
          requests:
            memory: "64Mi"        
            cpu: "250m"           
          limits:
            memory: "128Mi"       
            cpu: "500m"
        ports:
        - containerPort: 8080

