// For namespace " dev "

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-developer
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: developer
  template:
    metadata:
      labels:
        app: develepor
    spec:
      containers:
        - name: container-developer
          image: nginx
          ports:
            - containerPort: 8090
  strategy:
    type: RollingUpdate
