apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  namespace: test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: your-image:tag
        resources:                
          requests:
            memory: "64Mi"        
            cpu: "250m"           
          limits:
            memory: "128Mi"       
            cpu: "500m"
        ports:
        - containerPort: 8080

