apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-developer
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: production
  template:
    metadata:
      labels:
        app: developer
    spec:
      containers:
        - name: container-developer
          image: nginx
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 8090
  strategy:
    type: RollingUpdate
