apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploydev
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: multi
  template:
    metadata:
      labels:
        app: multi
    spec:
      containers:
        - name: multi-pipline
          image: nginx
          ports:
            - containerPort: 8090
  strategy:
    type: RollingUpdate
