apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploym
  namespace: test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: jenk-lap
          image: nginx
          ports:
            - containerPort: 8090
  strategy:
    type: RollingUpdate
