apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploytest
  namespace: test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: multi
  template:
    metadata:
      labels:
        app: multi
    spec:
      containers:
        - name: multi-pipline
          image: nginx
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 8090
  strategy:
    type: RollingUpdate
