apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-production
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-production
            port:
              number: 80
